task:
  container:
    image: $ELECTRUM_IMAGE
    cpu: 1
    memory: 1G
  matrix:
    - name: Tox Python $ELECTRUM_PYTHON_VERSION
      env:
        ELECTRUM_IMAGE: python:$ELECTRUM_PYTHON_VERSION
        TOXENV: py3
        ELECTRUM_PYTHON_NAME: python3
      matrix:
       - env:
           ELECTRUM_PYTHON_VERSION: 3.8
       - env:
           ELECTRUM_PYTHON_VERSION: 3.9
       - env:
           ELECTRUM_PYTHON_VERSION: 3.10
       - env:
           ELECTRUM_PYTHON_VERSION: 3
       - env:
           ELECTRUM_PYTHON_VERSION: rc
    - name: Tox PyPy
      allow_failures: true
      env:
        ELECTRUM_IMAGE: pypy:3
        TOXENV: pypy3
        ELECTRUM_PYTHON_NAME: pypy3
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $ELECTRUM_IMAGE && cat $ELECTRUM_REQUIREMENTS_CI && cat $ELECTRUM_REQUIREMENTS
  version_script:
    - $ELECTRUM_PYTHON_NAME --version
  tag_script:
    - git tag
  install_script:
    - apt-get update
    - apt-get -y install libsecp256k1-0
    - pip install -r $ELECTRUM_REQUIREMENTS_CI
  tox_script:
    - tox
  coveralls_script:
    - if [ ! -z "$COVERALLS_REPO_TOKEN" ] ; then coveralls ; fi
  env:
    ELECTRUM_REQUIREMENTS_CI: contrib/requirements/requirements-ci.txt
    ELECTRUM_REQUIREMENTS: contrib/requirements/requirements.txt
    # following CI_* env vars are set up for coveralls
    CI_NAME: "CirrusCI"
    CI_BUILD_NUMBER: $CIRRUS_BUILD_ID
    CI_JOB_ID: $CIRRUS_TASK_ID
    CI_BUILD_URL: "https://cirrus-ci.com/task/$CIRRUS_TASK_ID"
    CI_BRANCH: $CIRRUS_BRANCH
    CI_PULL_REQUEST: $CIRRUS_PR
    # in addition, COVERALLS_REPO_TOKEN is set as an "override" in https://cirrus-ci.com/settings/...

task:
  name: Locale
  container:
    image: $ELECTRUM_IMAGE
    cpu: 1
    memory: 1G
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo Locale && echo $ELECTRUM_IMAGE && cat $ELECTRUM_REQUIREMENTS_CI
  install_script:
    - apt-get update
    - apt-get -y install gettext
    - pip install -r $ELECTRUM_REQUIREMENTS_CI
    - pip install requests
  locale_script:
    - contrib/push_locale
  env:
    ELECTRUM_IMAGE: python:3.8
    ELECTRUM_REQUIREMENTS_CI: contrib/requirements/requirements-ci.txt
    # in addition, crowdin_api_key is set as an "override" in https://cirrus-ci.com/settings/...
  depends_on:
    - Tox Python 3.9
  only_if: $CIRRUS_BRANCH == 'master'
